plugins {
    id 'com.android.application'
}

android {
    namespace 'top.misaknetwork.bilixia'
    compileSdk 34

    defaultConfig {
        applicationId "top.misaknetwork.bilixia"
        minSdk 26
        targetSdk 34
        versionCode 7
        versionName "1.7"
        ndk {
            abiFilters 'arm64-v8a'
        }
         packagingOptions {
        jniLibs {
            // 关掉剥离调试符号，避免那些警告
            useLegacyPackaging = true
        }
    }
}
    }

    signingConfigs {
        release {
            def ksPath = System.getenv("KEYSTORE_FILE")
                    ?: "${System.getProperty('user.home')}/biliXia-release.jks"
            storeFile file(ksPath)
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }


dependencies {
    implementation 'com.arthenica:smart-exception-java:0.2.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.activity:activity:1.8.2'
    implementation 'dev.ffmpegkit-maintained:ffmpeg-kit-full:8.1.7'
}