-keep class com.arthenica.ffmpegkit.** { *; }
-keep class com.arthenica.smartexception.** { *; }
-keep class com.arthenica.** { *; }
-dontwarn com.arthenica.**
-keep class dev.ffmpegkit.** { *; }
-dontwarn dev.ffmpegkit.**
-keep class androidx.activity.result.** { *; }
-keep class top.misaknetwork.bilixia.** { *; }